-- FILE: 01 - Create Users Table.sql
-- TOPIC: CH24 - Login Register and Authentication with MySQL

-- GOAL:
-- - Create a users table for register and login examples.
-- - Store hashed passwords, not plain text passwords.

-- HOW TO USE:
-- 1. Open phpMyAdmin.
-- 2. Create or select the database named php_note_db.
-- 3. Run this SQL file.

CREATE TABLE IF NOT EXISTS users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Explanation:
-- user_id:
--   A unique ID for each user.
--
-- username:
--   The display name of the user.
--
-- email:
--   The login email. It is UNIQUE so two users cannot use the same email.
--
-- password:
--   Stores the hashed password generated by password_hash().
--   Never store plain text passwords in a real system.
--
-- created_at:
--   Automatically stores the account creation time.
