<?php
/*
  FILE: 02 - PHP Inside HTML.php
  TOPIC: CH01 - PHP Introduction and Setup

  GOAL:
  - Learn how PHP can be written inside an HTML page.
  - Learn how PHP can create dynamic page content.
  - Understand the difference between static HTML and dynamic PHP output.

  IMPORTANT:
  - HTML is sent to the browser as page structure.
  - PHP runs on the server and generates output.
  - PHP can be placed in different parts of an HTML document.
*/


/*
  These variables store values that will be inserted into the HTML below.
  This makes the page dynamic because the displayed values come from PHP.
*/

$pageTitle = "PHP Inside HTML";
$studentName = "Galen";
$currentTopic = "Embedding PHP in HTML";
$learningStatus = "In Progress";

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <!--
      Safe example inside HTML comment:
      &lt;?php echo "This is PHP inside HTML"; ?&gt;

      We use &lt; and &gt; so the server will not read the example as real PHP.
    -->

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CH01 - PHP Inside HTML</title>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="../global.css">
</head>
<body>

    <div class="container">

        <h1><?php echo $pageTitle; ?></h1>

        <div class="box output">
            <h2>Dynamic Content Generated by PHP</h2>

            <p>
                Student Name:
                <strong><?php echo $studentName; ?></strong>
            </p>

            <p>
                Current Topic:
                <strong><?php echo $currentTopic; ?></strong>
            </p>

            <p>
                Learning Status:
                <strong><?php echo $learningStatus; ?></strong>
            </p>
        </div>

        <div class="box">
            <h2>How This Works</h2>

            <p>
                The HTML structure is written normally.
                Then PHP is inserted only at the places where dynamic content is needed.
            </p>

            <pre>&lt;p&gt;
    Student Name:
    &lt;strong&gt;&lt;?php echo $studentName; ?&gt;&lt;/strong&gt;
&lt;/p&gt;</pre>
        </div>

        <div class="box note">
            <h2>When Is This Useful?</h2>

            <p>
                This technique is useful when the page layout is mostly HTML,
                but some values need to come from PHP variables, forms, sessions,
                or databases.
            </p>
        </div>
        <nav class="lesson-nav" aria-label="Lesson navigation">
            <a class="previous" href="01 - First PHP Script.php">&lsaquo; Previous: 01 - First PHP Script.php</a>
            <a class="next" href="03 - Echo and Print.php">Next: 03 - Echo and Print.php &rsaquo;</a>
        </nav>

    </div>

</body>
</html>
