<?php
/*
  FILE: 07 - CSRF Token Basic Demo.php
  TOPIC: CH25 - Security Basics for Backend PHP

  GOAL:
  - Learn what a CSRF token is.
  - Learn how to generate a token and store it in session.
  - Learn how to verify the token when a form is submitted.

  CSRF MEANING:
  - CSRF stands for Cross-Site Request Forgery.
  - It is when another site tries to submit a request as if it came from the user.

  BASIC IDEA:
  - Generate a random token.
  - Store it in session.
  - Put the token in the form as a hidden input.
  - When the form is submitted, compare the submitted token with the session token.
*/

session_start();

if (!isset($_SESSION["csrf_token"])) {
    /*
      random_bytes(32) generates secure random bytes.
      bin2hex() converts those bytes into readable hexadecimal text.
    */

    $_SESSION["csrf_token"] = bin2hex(random_bytes(32));
}

$csrfToken = $_SESSION["csrf_token"];
$message = "";
$messageClass = "";
$submittedTitle = $_POST["title"] ?? "";
$submittedToken = $_POST["csrf_token"] ?? "";

if ($_SERVER["REQUEST_METHOD"] === "POST") {
    /*
      hash_equals() compares two strings safely.

      It is better than using == for security-sensitive token comparison.
    */

    if (hash_equals($csrfToken, $submittedToken)) {
        $message = "Form submitted successfully. CSRF token is valid.";
        $messageClass = "success";

        /*
          Optional habit:
          Generate a new token after successful submission.
          This makes the submitted token single-use.
        */

        $_SESSION["csrf_token"] = bin2hex(random_bytes(32));
        $csrfToken = $_SESSION["csrf_token"];
    } else {
        $message = "Form rejected. CSRF token is invalid.";
        $messageClass = "error";
    }
}

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CH25 - CSRF Token Basic Demo</title>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="../global.css">
</head>
<body>

    <div class="container">

        <h1>CH25 - CSRF Token Basic Demo</h1>

        <p>
            A CSRF token helps confirm that the form submission came from the page generated by your application.
        </p>

        <?php if ($message !== "") { ?>
            <div class="box <?= htmlspecialchars($messageClass) ?>">
                <h2>Submission Result</h2>
                <p><?= htmlspecialchars($message) ?></p>
            </div>
        <?php } ?>

        <div class="box">
            <h2>Protected Form</h2>

            <form method="POST">
                <!--
                  The token is included as a hidden input.
                  Do not write raw PHP tags inside an HTML comment.
                  Example should be escaped like this: &lt;?php echo $csrfToken; ?&gt;
                -->

                <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>">

                <label for="title">Post Title</label>
                <input type="text" id="title" name="title" value="<?= htmlspecialchars($submittedTitle) ?>">

                <button type="submit">Submit Protected Form</button>
            </form>
        </div>

        <div class="box output">
            <h2>Current Token</h2>

            <p>
                This is shown for learning only. In real systems, normal users do not need to see the token.
            </p>

            <pre><?= htmlspecialchars($csrfToken) ?></pre>
        </div>

        <div class="box note">
            <h2>Important Code Pattern</h2>

            <pre><?= htmlspecialchars('$_SESSION["csrf_token"] = bin2hex(random_bytes(32));') ?></pre>
            <pre><?= htmlspecialchars('hash_equals($_SESSION["csrf_token"], $_POST["csrf_token"])') ?></pre>
        </div>
        <nav class="lesson-nav" aria-label="Lesson navigation">
            <a class="previous" href="06 - Session Protection.php">&lsaquo; Previous: 06 - Session Protection.php</a>
        </nav>

    </div>

</body>
</html>
