<?php
/*
  FILE: 06 - Loop with HTML Table.php
  TOPIC: CH06 - Loops

  GOAL:
  - Learn how PHP loops generate repeated HTML output.
  - Learn how to display array data in an HTML table.
  - Prepare for future MySQL SELECT display examples.

  IMPORTANT:
  In backend PHP, one of the most common jobs is:
  1. Get many records from a database.
  2. Loop through the records.
  3. Display each record as an HTML table row.
*/

/*
  This array simulates database records.

  Later in MySQL chapters, the data will come from a database table.
  For now, we use a normal PHP array so that we can focus on loop logic first.
*/

$products = [
    ["id" => 1, "name" => "Notebook", "category" => "Stationery", "price" => 4.50, "stock" => 25],
    ["id" => 2, "name" => "Pen", "category" => "Stationery", "price" => 1.20, "stock" => 80],
    ["id" => 3, "name" => "Mouse", "category" => "Computer", "price" => 35.00, "stock" => 12],
    ["id" => 4, "name" => "Keyboard", "category" => "Computer", "price" => 55.00, "stock" => 8],
    ["id" => 5, "name" => "Bottle", "category" => "Daily Use", "price" => 12.90, "stock" => 0]
];

/*
  Calculate total inventory value.

  Formula:
  product price x stock quantity
*/

$totalInventoryValue = 0;

foreach ($products as $product) {
    $totalInventoryValue += $product["price"] * $product["stock"];
}

/*
  Count how many products are out of stock.
*/

$outOfStockCount = 0;

foreach ($products as $product) {
    if ($product["stock"] == 0) {
        $outOfStockCount++;
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <!--
      This file is a PHP file that outputs HTML.

      Important:
      If we want to show PHP syntax inside an HTML comment,
      we should escape the PHP opening tag.

      Safe example inside HTML comment:
      &lt;?php echo "Hello World"; ?&gt;

      Do not write the real PHP opening tag inside an HTML comment
      when you only want to display it as text.
    -->

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CH06 - Loop with HTML Table</title>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="../global.css">
</head>
<body>

    <div class="container">

        
        <div class="page-card">
            <h1>CH06 - Loop with HTML Table</h1>

        <div class="box example">
            <h2>Why Loop with HTML?</h2>

            <p>
                A loop can generate repeated HTML elements automatically.
                This is very useful when displaying many records, such as students, products, orders, or customers.
            </p>
        </div>

        <div class="box output">
            <h2>Product Table</h2>

            <table>
                <tr>
                    <th>ID</th>
                    <th>Product Name</th>
                    <th>Category</th>
                    <th>Price</th>
                    <th>Stock</th>
                    <th>Status</th>
                    <th>Total Value</th>
                </tr>

                <?php foreach ($products as $product) { ?>
                    <tr>
                        <td><?php echo $product["id"]; ?></td>
                        <td><?php echo htmlspecialchars($product["name"]); ?></td>
                        <td><?php echo htmlspecialchars($product["category"]); ?></td>
                        <td>RM <?php echo number_format($product["price"], 2); ?></td>
                        <td><?php echo $product["stock"]; ?></td>
                        <td>
                            <?php
                                if ($product["stock"] > 0) {
                                    echo "Available";
                                } else {
                                    echo "Out of Stock";
                                }
                            ?>
                        </td>
                        <td>
                            RM <?php echo number_format($product["price"] * $product["stock"], 2); ?>
                        </td>
                    </tr>
                <?php } ?>
            </table>
        </div>

        <div class="box output">
            <h2>Summary Generated by Loops</h2>

            <p>
                <strong>Total Products:</strong>
                <?php echo count($products); ?>
            </p>

            <p>
                <strong>Out of Stock Products:</strong>
                <?php echo $outOfStockCount; ?>
            </p>

            <p>
                <strong>Total Inventory Value:</strong>
                RM <?php echo number_format($totalInventoryValue, 2); ?>
            </p>
        </div>

        <div class="box warning">
            <h2>Connection to MySQL</h2>

            <p>
                This example uses a PHP array as sample data.
                In later database chapters, the same table display pattern will be used with MySQL records.
            </p>
        </div>
            <nav class="lesson-nav" aria-label="Lesson navigation">
                <a class="previous" href="05 - Break and Continue.php">&lsaquo; Previous: 05 - Break and Continue.php</a>
                <a class="next" href="../CH07 - Arrays/01 - Indexed Array.php">Next: 01 - Indexed Array.php &rsaquo;</a>
            </nav>

        </div>
    </div>

</body>
</html>
